---
title: "SERDP Project Installation Report"
author: "W.W. Dillon"
date: "9/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(message = F)

library(plyr); library(dplyr); library(ggplot2); library(readr)
library(stringi)
library(tidyr)
library(viridisLite); library(viridis)

```

## Project #: RC-2636

```{r set installation name}
inst_name = "Fort Jackson"
```

```{r load plot visit data}

```

```{r relative plots visited}


plot_nums <- plot_visit_data %>%
      group_by(installation_full_name) %>% 
      summarise(plot_ct = n_distinct(plot_id)) %>% 
      mutate(installation_flag = ifelse(installation_full_name==inst_name,T,F))
plot_nums <- left_join(
      plot_nums,
      plot_visit_data
)

      ggplot(aes(installation_full_name, plot_ct, label=plot_ct)) +
      geom_col(aes(color = installation_flag), size = 4, show.legend = F) +
      geom_col(aes(fill = imcy_inv)) +
      scale_color_manual(values = c("TRUE" = "blue", "FALSE" = NA)) +
      invasion_fill +
      # geom_text(nudge_y = 0) +
      # scale_fill_manual(values = c(installation_name = "blue")) +
      # facet_grid(installation_full_name ~ ., scales = "free_y") +
      ylab("Number of sample plots") +
      xlab("") +
      # ggtitle("Plots in Burn Units Across Installations") +
      theme_classic() +
      def_theme +
      # theme(lege) +
      NULL
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
