---
title: "FABIO - Annotated Bibliography"
author: "W.W. Dillon"
date: "1/17/2019"
output: html_document
bibliography: 
      - knitcitations.bib
      - references.bib
csl: bib_styles/chicago-annotated-bibliography.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

# devtools::install_github("crsh/citr")

library(knitcitations)
library(RefManageR)

```

@VarnerFlammabilityForestWoodland2015

This is a review and synthesis of findings on flammability of litter, focusing in particular on leaf litter in forest systems. 

> The intent of this review is to synthesize the existing research to (1) review the evidence for mechanistic drivers of litter flam- mability, (2) compare and critique methodologies and measure- ments used to assess litter flammability, (3) evaluate the needs and impediments to scaling up laboratory findings to the field level, (4) revisit relevant concepts and components of litter flammability, and (5) provide areas for future research.

Of specific interest for the FABIO method is number 3: **evalute the needs and impediments to scaling up laboratory findings to the field level**.

Paraphrasing: "linking lab-based measurements to field-based observations and measurements remains a challenge."

Propose regularly describing flammability metrics separately rather than using the terms of flammability (ignitability, combustibility, sustainability, consumability), which they argue are more confusing than clarifying. In laboratory flammability studies fuel-loading is controlled to evaluate species-specific/community-specific differences and so spread evenly across an area. This eliminates variability in fuel loading that occurs at small spatial scales. Methods altering or eliminating physical or biochemical traits require cautious interpretation because they are typically far outside the range of real-worl conditions.


@Fernandes2012

This study focuses on flammability/fire in shrub ecosystems. Flammability studies have predominantly focused on examining whether plant traits may confer fitness in fire-prone environments. These experiments are typically not good surrogates for real-world, full-scale fire behavior, i.e. they are limited by the scale of the experiment. Experiments that replicate heat flux environment and plant structure provide flammability metrics that are more relevant to real-world systems. They call for the reconstructed fuel complext to emulate natural fuel structure as closely as possible; flammability metrics should closely correspond to field measurements. On the flip-side, there are substantial limitations to outdoor experimental fires due to operational, safety, and cost. 

While this paper picks on the limitations of laboratory experiments to inform fire behavior models, which is often not the intention of these experiments, I think it's fair to point out that laboratory experiments could produce added value by making flammability measurements that correspond to the field whenever feasible.


@GanteaumeFlammabilitylittersampled2014

They present results showing that flammability measurements from "reconstructed" fuel beds in lab experiments differed from "intact" fuelbeds collected from the field.


# Temperatures recorded during grass fires


**@clements2007observing Observing the dynamics of wildland grass fires: FireFlux - A field validation experiment.**

 - Maximum ranging from 752 - 835 ºC

**Bailey & Anderson 1980. Fire temperatures in grass, shrub, and aspen forest communities of central Alberta**

 - Grassland average maximum temperature 186 ± 10 S.E. measured using temperature pellets at heights of 0, 5, 15, 30, and 45 cm

**Ramsay & Oxley 1996. Fire temperatures and postfire plant community dynamics in Ecuadorian grass páramo**

 - "sometimes >500 ºC" using temperature crayons ranging from 65-670 ºC at 1 m, 65 cm, 35 cm, and 5 cm above ground level.
 
 - Temperatures were recorded within the grass tussocks. Highest temperatures occurred int he upper leaves of the tussocks and the lowest temperatures at the base of the tussocks
