---
title: "SERDP Data Dictionary"
author: "Steven Cabrera"
date: "October 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra)
```

# Common among all dataframes

```{r common parameters across all data, echo=FALSE}

common_fields <- data.frame(
  field_name = c("plot_id", "date", "visit_year"),
  data_type = c(
    "character", "date", "numeric"),
  description = c("installation name and an assigned letter for the plot",
    "date that set of data was collected. format: YYYY-MM-DD", 
    "year the plot was visited"))

kable(common_fields) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, border_right = T)
  

```

# Plot visit and invasion status

```{r plot visit & invasion status, echo=FALSE}

plot_visit_cogon_fields <- data.frame(
  field_name = c("imcy_inv", "avg_tiller_density_m2", "xcoord_lon", "ycoord_lat",
                 "years_since_fire"),
  data_type = c(
    "character", "numeric", "numeric", "numeric", "numeric"),
  description = c("invasion status of *Imperata cylindrica*",
    "average number of *Imperata cylindrica* tillers per square meter", 
    "longitudinal x-coordinate of plot_id", "latitudinal y-coordinate of plot_id", 
    "number of years since sample area was last burned"))

kable(plot_visit_cogon_fields) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, border_right = T)

```

# Vegetation - quadrat plant species

```{r vegatation plant species of 1m quadrats, echo=FALSE}

quadrat_species_fields <- data.frame(
  field_name = c("species_name", "functional_group" , "avg_pct_cover", "num_stems_m2"),
  data_type = c(
    "character", "character", "numeric", "numeric"),
  description = c("species of the individals to at least Genus level. if NA, unable to      identify.",
    "functional group of the species. ex: graminoid, forb, shrub, tree", 
    "estimate of the species' percent cover in the plot based on an average of four square meter quadrats", 
    "estimate of the species' number of stems in the plot based on an average of four square meter quadrats"))

kable(quadrat_species_fields) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, border_right = T)

```

# Vegetation - quadrat, biomass, and canopy cover 

```{r vegetation data in 1m quadrats, biomass, and canopy cover, echo=FALSE}

quadrat_biomass_canopy_fields <- data.frame(
  field_name = c("avg_woody_veg_ht", "avg_herb_veg_ht", "avg_litter_ht", "avg_pct_green", "avg_pct_litter", "avg_pct_wood_litter", "avg_pct_bare", "avg_standing_fuel_mass_wet_m2", "avg_litter_mass_wet_m2", "avg_standing_fuel_mass_dry_m2", "avg_litter_mass_dry_m2", "avg_pct_canopy_cover"),
  data_type = c(
    "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"),
  description = c("invasion status of *Imperata cylindrica*",
    "average number of *Imperata cylindrica* tillers per square meter", 
    "longitudinal x-coordinate of plot_id", 
    "latitudinal y-coordinate of plot_id", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned"))

kable(quadrat_biomass_canopy_fields) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, border_right = T)

```

# Trees raw

```{r raw tree data, echo=FALSE}

trees_raw_fields <- data.frame(
  field_name = c("tag", "species_name", "dbh", "canopy", "health", "distance", "azimuth", "height", "char"),
  data_type = c(
    "numeric", "character", "numeric", "character", "character", "numeric", "numeric", "numeric", "numeric"),
  description = c("invasion status of *Imperata cylindrica*",
    "average number of *Imperata cylindrica* tillers per square meter", 
    "longitudinal x-coordinate of plot_id", 
    "latitudinal y-coordinate of plot_id", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned"))

kable(trees_raw_fields) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, border_right = T)

```

# Tree summary

```{r summarized tree data to plot level, echo=FALSE}

trees_summary_fields <- data.frame(
  field_name = c( "species_name", "canopy", "health", "total_dbh", "avg_height", "avg_char"),
  data_type = c(
    "character", "character", "character", "numeric", "numeric", "numeric"),
  description = c("invasion status of *Imperata cylindrica*",
    "average number of *Imperata cylindrica* tillers per square meter", 
    "longitudinal x-coordinate of plot_id", 
    "latitudinal y-coordinate of plot_id", 
    "number of years since sample area was last burned", 
    "number of years since sample area was last burned"))

kable(trees_summary_fields) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, border_right = T)

```

# Woody subplot

```{r woody subplot, echo=FALSE}

woody_subplot_fields <- data.frame(
  field_name = c("species_name", "stems_100m2"),
  data_type = c(
    "character", "numeric"),
  description = c("invasion status of *Imperata cylindrica*",
    "average number of *Imperata cylindrica* tillers per square meter"))

kable(woody_subplot_fields) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, border_right = T)

```

# Ticks

```{r ticks, echo=FALSE}

ticks_fields <- data.frame(
  field_name = c("species", "life_stage", "tick_count"),
  data_type = c(
    "character", "character", "numeric"),
  description = c("invasion status of *Imperata cylindrica*",
    "average number of *Imperata cylindrica* tillers per square meter", 
    "longitudinal x-coordinate of plot_id"))

kable(ticks_fields) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, border_right = T)

```

# Dung

```{r dung, echo=FALSE}

dung_fields <- data.frame(
  field_name = c("species", "dung1m", "dung2m"),
  data_type = c(
    "character", "numeric", "numeric"),
  description = c("invasion status of *Imperata cylindrica*",
    "average number of *Imperata cylindrica* tillers per square meter", 
    "longitudinal x-coordinate of plot_id"))

kable(dung_fields) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, border_right = T)

```
